### ISSUE TITLE
THANKS!

### ISSUE THREAD

**Issue by ghost** [OnePlusOSS/android#1]
Thanks for doing this, very important step! 💃 

also can you make sure a License file is included? 👍

**Comment by handelxh** [comment]
i can not get the oneplus android sdk by this CMD :  repo  init -u git://github.com/OnePlusOSS/android .git -b oneplus3/6.0.1   

>     fatal: Cannot get https://code.google.com/p/git-repo/clone.bundle

> fatal:  error [Errno -2] Name or service not known

**Comment by handelxh** [comment]
In  china , because of GWF ,repo can not work, so must follow this CMD : 

> repo init -u git://github.com/OnePlusOSS/android.git -b oneplus3/6.0.1 --repo-url=https://review.mfunz.com/git-repo --repo-branch=stable
> 
> repo sync

`
