### ISSUE TITLE
请问一下有N的源码吗？

### ISSUE THREAD

**Issue by beefsea** [OnePlusOSS/android#12]
请问一下有N的源码吗？

**Comment by aaronqiuchiu** [comment]
Please below
https://github.com/OnePlusOSS/android_kernel_oneplus_msm8996

**Comment by aaronqiuchiu** [comment]
https://github.com/OnePlusOSS/android_kernel_oneplus_msm8998
https://github.com/OnePlusOSS/android_kernel_oneplus_msm8996
