### ISSUE TITLE
ninja: error: 'vendor/oneplus/sbin/dashd'

### ISSUE THREAD

**Issue by 0x10000** [OnePlusOSS/android#15]
When I compile QC8996_N_7.1 branch got this message.
I can't find /sbin/dashd in my phone.
My OS version is OOS 4.1.3(7.1.1)

**Comment by MegaLiu** [comment]
Hi 0x10000,

Could you follow the instruction written below the link to root the device and pull the necessary libraries from your device by executing the script pull_library.sh?
https://github.com/OnePlusOSS/android
 
Please remember to root your device first, otherwise permission will be denied when you try to access sbin folder. Thanks.

Regards,
David Liu

**Comment by 0x10000** [comment]
@MegaLiu 
Yes,that's right.But when I copy the libs in root , also have some files missing.I'm not sure if it affects compilation.

cp: /system/bin/kernel-tests/smd_pkt_loopback_test: No such file or directory
cp: bad '/system/bin/kernel-tests/smd_pkt_loopback_test': No such file or directory
cp: /system/bin/kernel-tests/smd_tty_loopback_test: No such file or directory
cp: bad '/system/bin/kernel-tests/smd_tty_loopback_test': No such file or directory
cp: /system/bin/kernel-tests/smem_log_test: No such file or directory
cp: bad '/system/bin/kernel-tests/smem_log_test': No such file or directory
cp: /system/bin/qmi-framework-tests/check_system_health: No such file or directory
cp: bad '/system/bin/qmi-framework-tests/check_system_health': No such file or directory
cp: /sdcard/vendor/oneplus/bin/qmi-framework-tests/qmi_test_mt_client_init_instance: No such file or directory
cp: /system/bin/qmi-framework-tests/qmi_test_service_clnt_test_0000: No such file or directory
cp: bad '/system/bin/qmi-framework-tests/qmi_test_service_clnt_test_0000': No such file or directory
cp: /system/bin/qmi-framework-tests/qmi_test_service_clnt_test_0001: No such file or directory
cp: bad '/system/bin/qmi-framework-tests/qmi_test_service_clnt_test_0001': No such file or directory
cp: /system/bin/qmi-framework-tests/qmi_test_service_clnt_test_1000: No such file or directory
cp: bad '/system/bin/qmi-framework-tests/qmi_test_service_clnt_test_1000': No such file or directory
cp: /system/bin/qmi-framework-tests/qmi_test_service_clnt_test_1001: No such file or directory
cp: bad '/system/bin/qmi-framework-tests/qmi_test_service_clnt_test_1001': No such file or directory
cp: /system/bin/qmi-framework-tests/qmi_test_service_clnt_test_2000: No such file or directory
cp: bad '/system/bin/qmi-framework-tests/qmi_test_service_clnt_test_2000': No such file or directory
cp: /system/bin/qmi-framework-tests/qmi_test_service_test: No such file or directory
cp: bad '/system/bin/qmi-framework-tests/qmi_test_service_test': No such file or directory
/
cp: /system/vendor/etc/qti-logkit/IMS.dmc: No such file or directory
cp: bad '/system/vendor/etc/qti-logkit/IMS.dmc': No such file or directory
cp: /system/vendor/etc/qti-logkit/audiobasic.dmc: No such file or directory
cp: bad '/system/vendor/etc/qti-logkit/audiobasic.dmc': No such file or directory
cp: /system/vendor/etc/qti-logkit/gnsslocationlogging.dmc: No such file or directory
cp: bad '/system/vendor/etc/qti-logkit/gnsslocationlogging.dmc': No such file or directory
cp: /system/vendor/etc/qti-logkit/goldenlogmask.dmc: No such file or directory
cp: bad '/system/vendor/etc/qti-logkit/goldenlogmask.dmc': No such file or directory
cp: /system/vendor/etc/qti-logkit/qti_logkit_command.xml: No such file or directory
cp: bad '/system/vendor/etc/qti-logkit/qti_logkit_command.xml': No such file or directory
cp: /system/vendor/etc/qti-logkit/qti_logkit_config.xml: No such file or directory
cp: bad '/system/vendor/etc/qti-logkit/qti_logkit_config.xml': No such file or directory
cp: /system/vendor/etc/qti-logkit/scenarios/IMS.png: No such file or directory
cp: bad '/system/vendor/etc/qti-logkit/scenarios/IMS.png': No such file or directory
cp: /system/vendor/etc/qti-logkit/scenarios/bluetooth.png: No such file or directory
cp: bad '/system/vendor/etc/qti-logkit/scenarios/bluetooth.png': No such file or directory
cp: /system/vendor/etc/qti-logkit/scenarios/default.png: No such file or directory
cp: bad '/system/vendor/etc/qti-logkit/scenarios/default.png': No such file or directory
cp: /sdcard/vendor/oneplus/vendor/framework/qti-vzw-ims-internal.jar: No such file or directory

**Comment by rancidfrog** [comment]
@MegaLiu There are many errors and some permission denied when running script: https://hastebin.com/ragebabojo.sql

Phone rooted
But, there is an error with pull script as it keeps giving error permission denied:
```
adb: error: failed to copy '/sbin/dashd' to 'vendor/oneplus/sbin/dashd': remote open failed: Permission denied

```
**Changes to pull_script.sh needed!**
Also,**` adb root`** does not work: `adbd cannot run as root in production builds`

**Comment by ghost** [comment]
Adb root only works in engineering builds

**Comment by rancidfrog** [comment]
@anupritaisno1 ???

Does not change anything. Seems like repos are not updated as many files` do not exist`,
and dashd needs some magic to copy.
I was able to do it with adb shell | su | copy to sdcard then copy it to pc.
But, still **_pull_script.sh_** needs to be updated: https://hastebin.com/ragebabojo.sql
@MegaLiu 
**EDIT:** _Complete list of errors,_
```
$ ./pull_library.sh
adb: error: remote object '/system/bin/adsprpcd' does not exist
adb: error: remote object '/system/bin/ATFWD-daemon' does not exist
adb: error: remote object '/system/bin/athdiag' does not exist
adb: error: remote object '/system/bin/btnvtool' does not exist
adb: error: remote object '/system/bin/cnd' does not exist
adb: error: remote object '/system/bin/cnss-daemon' does not exist
adb: error: remote object '/system/bin/cnss_diag' does not exist

adb: error: remote object '/system/bin/diag_dci_sample' does not exist
adb: error: remote object '/system/bin/diag_klog' does not exist
adb: error: remote object '/system/bin/diag_mdlog' does not exist
adb: error: remote object '/system/bin/diag_socket_log' does not exist
adb: error: remote object '/system/bin/diag_uart_log' does not exist
adb: error: remote object '/system/bin/dpmd' does not exist
adb: error: remote object '/system/bin/DR_AP_Service' does not exist
adb: error: remote object '/system/bin/dun-server' does not exist
adb: error: remote object '/system/bin/energy-awareness' does not exist

adb: error: remote object '/system/bin/garden_app' does not exist
adb: error: remote object '/system/bin/gpsone_daemon' does not exist

adb: error: remote object '/system/bin/hal_proxy_daemon' does not exist

adb: error: remote object '/system/bin/hvdcp_opti' does not exist
adb: error: remote object '/system/bin/imscmservice' does not exist
adb: error: remote object '/system/bin/imsdatadaemon' does not exist
adb: error: remote object '/system/bin/imsqmidaemon' does not exist
adb: error: remote object '/system/bin/ims_rtp_daemon' does not exist
adb: error: remote object '/system/bin/iop' does not exist
adb: error: remote object '/system/bin/ipacm-diag' does not exist

adb: error: remote object '/system/bin/irsc_util' does not exist

adb: error: remote object '/system/bin/loc_launcher' does not exist
adb: error: remote object '/system/bin/lowi-server' does not exist

adb: error: remote object '/system/bin/mmi' does not exist

adb: error: remote object '/system/bin/mm-qcamera-daemon' does not exist

adb: error: remote object '/system/bin/msm_irqbalance' does not exist

adb: error: remote object '/system/bin/netmgrd' does not exist

adb: error: remote object '/system/bin/pktlogconf' does not exist
adb: error: remote object '/system/bin/PktRspTest' does not exist
adb: error: remote object '/system/bin/pm-proxy' does not exist
adb: error: remote object '/system/bin/pm-service' does not exist
adb: error: remote object '/system/bin/port-bridge' does not exist

adb: error: remote object '/system/bin/qseecomd' does not exist
adb: error: remote object '/system/bin/qseecom_sample_client' does not exist
adb: error: remote object '/system/bin/qvop-daemon' does not exist

adb: error: remote object '/system/bin/rmt_storage' does not exist
adb: error: remote object '/system/bin/secure_ui_sample_client' does not exist
adb: error: remote object '/system/bin/seempd' does not exist
adb: error: remote object '/system/bin/sensors.qcom' does not exist
adb: error: remote object '/system/bin/sns_ar_testapp' does not exist
adb: error: remote object '/system/bin/sns_cm_conc_test' does not exist
adb: error: remote object '/system/bin/sns_cm_test' does not exist
adb: error: remote object '/system/bin/sns_daf_test' does not exist
adb: error: remote object '/system/bin/sns_dsps_tc0001' does not exist
adb: error: remote object '/system/bin/sns_hal_batch' does not exist
adb: error: remote object '/system/bin/sns_oem_test' does not exist
adb: error: remote object '/system/bin/sns_regedit_ssi' does not exist

adb: error: remote object '/system/bin/spdaemon' does not exist
adb: error: remote object '/system/bin/ssr_diag' does not exist
adb: error: remote object '/system/bin/ssr_setup' does not exist
adb: error: remote object '/system/bin/StoreKeybox' does not exist
adb: error: remote object '/system/bin/subsystem_ramdump' does not exist

adb: error: remote object '/system/bin/test_diag' does not exist

adb: error: remote object '/system/bin/tftp_server' does not exist
adb: error: remote object '/system/bin/time_daemon' does not exist

adb: error: remote object '/system/bin/wcnss_filter' does not exist

adb: error: remote object '/system/bin/wfdservice' does not exist

adb: error: remote object '/system/bin/xtwifi-client' does not exist
adb: error: remote object '/system/bin/xtwifi-inet-agent' does not exist

adb: error: remote object '/system/bin/fingerprintd' does not exist
adb: error: remote object '/system/bin/ifaadaemon' does not exist

adb: error: remote object '/system/vendor/bin/esepmdaemon' does not exist
adb: error: remote object '/system/vendor/bin/hbtp_daemon' does not exist

adb: error: remote object '/system/vendor/bin/mdtpd' does not exist
adb: error: remote object '/system/vendor/bin/mm-pp-dpps' does not exist

adb: error: remote object '/system/vendor/bin/pd-mapper' does not exist
adb: error: remote object '/system/vendor/bin/perfd' does not exist

adb: error: remote object '/system/vendor/bin/qseeproxydaemon' does not exist
adb: error: remote object '/system/vendor/bin/qseeproxysampledaemon' does not exist
adb: error: remote object '/system/vendor/bin/qti' does not exist
adb: error: remote object '/system/vendor/bin/qvrservice' does not exist

adb: error: remote object '/system/vendor/bin/RIDLClient.exe' does not exist
adb: error: remote object '/system/vendor/bin/seemp_healthd' does not exist
adb: error: remote object '/system/vendor/bin/slim_daemon' does not exist
adb: error: remote object '/system/vendor/bin/smcinvoked' does not exist
adb: error: remote object '/system/vendor/bin/thermal-engine' does not exist

adb: error: failed to copy '/sbin/dashd' to 'vendor/oneplus/sbin/dashd': remote open failed: Permission denied
```

**Comment by rancidfrog** [comment]
@0x10000 
You can copy all missing files manually. Either by using File explorer with Root capabilities (FX:https://forum.xda-developers.com/showthread.php?p=72988357)
Or, using 
- `adb shell`
- `su`
- then `cp` each file from proper location to /sdcard

After copying the missing files manually from system using file explorer with root,
place them in correct folders under vendor/onplus

**Comment by robbins** [comment]
Is that the only fix? Getting each and every file manually? 

Is there no way for ADB root to run, even with ro.debuggable set to 1, and ro.secure to 0?

Or is there a fixed copy of the script somewhere, or a repo for the 5.0.1 OP3T vendor blobs?

Really sucks that OnePlus can't even take the time to have a working GitHub...

**Comment by robbins** [comment]
For anyone wondering, the solution is to set SELinux to Permissive. There's a Magisk Module to do exactly that. :)

**Comment by NEETESH10** [comment]
> Hi 0x10000,
> 
> Could you follow the instruction written below the link to root the device and pull the necessary libraries from your device by executing the script pull_library.sh? https://github.com/OnePlusOSS/android   Please remember to root your device first, otherwise permission will be denied when you try to access sbin folder. Thanks.
> 
> Regards, David Liu

please if anyone have boot image for rooting of oneplus nord 2 5G phone then please send or guide me how to and what to do
