### ISSUE TITLE
Repo sync project very slow

### ISSUE THREAD

**Issue by rancidfrog** [OnePlusOSS/android#18]
Following readme instructions:
```
Repo sync all code with default.xml
repo init -u git://github.com/OnePlusOSS/android.git -b oneplus/QC8998_N_7.1 repo sync
```
repo sync is very slow compared to all other projects, i.e. aosp/custom roms, etc.
Also, it is sycing many tags that are not needed.

Is there a way to sync only neeeded tags/branches?

**Comment by ghost** [comment]
Add --depth=1 to the end of the repo init command

**Comment by rancidfrog** [comment]
Thank you,
after re-initing repo with --depth=1 and doing forall git clean and prune, now syncing is much quicker.

**Comment by ghost** [comment]
You can also use --no-tags and --no-clone-bundle though I'm not really sure how these work
