### ISSUE TITLE
pull_library.sh missing files

### ISSUE THREAD

**Issue by joshchoo** [OnePlusOSS/android#24]
These files cannot be found on the device:

adb: error: failed to stat remote object '/system/lib64/hw/nfc_nci.pn54x.default.so': No such file or directory
adb: error: failed to stat remote object '/system/lib64/libnfc-nci.so': No such file or directory
adb: error: failed to stat remote object '/system/lib64/libnfc_nci_jni.so': No such file or directory
adb: error: failed to stat remote object '/system/vendor/lib64/libloc2jnibridge.so': No such file or directory

Are these still necessary?

**Comment by joshchoo** [comment]
My guess is that we should import the following:

/system/lib64/libnqnfc-nci.so
/system/lib64/libnqnfc_nci_jni.so

and delete the other two blobs

**Comment by desuvinodkumar** [comment]
Are you using OB16 or OBT17?

**Comment by joshchoo** [comment]
Thanks, I found the nfc_nci.pn54x.default.so in the latest OB. 

It still seems that '/system/vendor/lib64/libloc2jnibridge.so' is not present

**Comment by desuvinodkumar** [comment]
@joshuous libloc2jnibridge, Pls. ignore this error. Forgot to remove from the script. Thank you.

**Comment by desuvinodkumar** [comment]
removed libloc2jnibridge from script. Thank you
