### ISSUE TITLE
Missing module: libqc-skia

### ISSUE THREAD

**Issue by joshchoo** [OnePlusOSS/android#25]
error: external/skia/Android.bp:3:1: "libskia" depends on undefined module "libqc-skia"

**Comment by desuvinodkumar** [comment]
@joshuous , Sorry for inconvenience,  Pleas use these changes to build. Ihttps://github.com/OnePlusOSS/android_external_skia/commit/b5bb2d6cfb767598158d1e6a1124b3b18767fc69

**Comment by desuvinodkumar** [comment]
Updated the skia repo and Manifest. Verified Build and Boot. Thank you for reporting the error.
