### ISSUE TITLE
Where is OnePlus 6?

### ISSUE THREAD

**Issue by namoen0301** [OnePlusOSS/android#33]
[OnePlus Forum](https://forums.oneplus.com/threads/android-p-beta-and-device-tree-kernel-source-for-oneplus-6.833612/) announced:

> The device trees and kernel sources for the OnePlus 6 are available now on the OnePlus Github page. Go get them, and make sure to show the community what great custom software you can build!

But Where is it?

**Comment by mwilky** [comment]
Any update on when the device tree is going to be posted?

**Comment by anayw2001** [comment]
when Qualcomm has a presentation in a few weeks, I think

**Comment by maurisy0** [comment]
we're itching for the device tree, please OnePlus

**Comment by ghost** [comment]
Use itchguard

**Comment by robbins** [comment]
I'm interested in this too, as Qualcomm has already released the source code for SDM845

**Comment by aaronqiuchiu** [comment]
https://github.com/OnePlusOSS/android_kernel_oneplus_sdm845
