### ISSUE TITLE
Kernel sources missing for Oneplus 10T (SM8475)

### ISSUE THREAD

**Issue by yunoyunoyunoyuno** [OnePlusOSS/android#56]
The kernel sources for the OnePlus 10T with the SM8475 chipset are missing. Failing to publish the source code violates the GPL.

**Comment by yunoyunoyunoyuno** [comment]
@OnePlusOSSAdmin

**Comment by OnePlusOSSAdmin** [comment]
Please check following repo:
https://github.com/OnePlusOSS/android_kernel_oneplus_sm8475
https://github.com/OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8475

**Comment by yunoyunoyunoyuno** [comment]
Ok, closed. Next time, please act more quickly ^-^
